namespace GGMatch3
{
	public enum ChipType
	{
		Chip = 0,
		Bomb = 1,
		RandomChip = 2,
		HorizontalRocket = 3,
		VerticalRocket = 4,
		DiscoBall = 5,
		SeekingMissle = 6,
		EmptyChipSlot = 7,
		Box = 8,
		Chain = 9,
		BunnyChip = 10,
		CookiePickup = 11,
		FallingGingerbreadMan = 12,
		MagicHat = 13,
		PickupGrass = 14,
		BurriedElement = 15,
		Carpet = 16,
		IceOnChip = 17,
		GrowingElement = 18,
		GrowingElementPiece = 19,
		EmptyConveyorSpace = 20,
		MoreMovesChip = 21,
		RockBlocker = 22,
		BasketBlocker = 23,
		Unknown = 24,
		MonsterBlocker = 25,
		MagicHatBomb = 26,
		MagicHatSeekingMissle = 27,
		MagicHatRocket = 28,
		BasetBlockerWithBunny = 29,
		BoxEmpty = 30,
		BoxWithBurriedElement = 31,
		MonsterChip = 32,
		SnowRockBlocker = 33
	}
}
